name: openiothub_grpc_api
description: OpenioTHub Dart gRPC.
version: 1.0.0+1
homepage: https://github.com/OpenIotHUb/grpc

environment:
  sdk: ^3.0.0

dependencies:
  async: ^2.5.0
  googleapis_auth: ^1.1.0
  meta: ^1.3.0
  http: ^1.1.0
  http2: ^2.0.0
  #  grpc
  grpc: ^3.1.0
  #  grpc协议
  protobuf: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  lints: ^3.0.0
  mockito: ^5.0.0
  path: ^1.8.0
  test: ^1.16.0
  stream_channel: ^2.1.0
  stream_transform: ^2.0.0
